### ISSUE TITLE
Aim/purpose

### ISSUE THREAD

**Issue by dbosk** [dbosk/ecis-surveillance#1]
The workshop website: http://ecis2019.eu/programme/workshops-and-tutorials/surveillance-in-the-digital-society-1.421392

> The workshop should be seen as a springboard for ideas and early-stage manuscripts.

> The workshop invites short papers that reflect upon surveillance in the digital society by looking at how these practices are constructed, organised, experienced and regulated.

> - Self-surveillance - The attention one pays to one’s behaviour whilst, actuality or virtuality, being observed.
> - Organizational surveillance - Digitized work-places enabling  the monitoring of employees, partners, and customers posing ethical dilemmas
> - Societal surveillance - The disproportionate, unlimited citizen online monitoring, enabled by new anti-terrorism laws, criticized for turning citizens into suspects.
> - Sousveillance - The act of surveilling others as they surveil you
> - Resistance towards surveillance - The use of strategies to avoid or disrupt the surveillance mechanisms

**Comment by sbuc** [comment]
What comes to mind first is some short exploration of services that
usually imply surveillance when one uses them and attempts to remove the
surveillance part. How to have one's cake and eat it too - in private.
E.g., location-based services by distance-bounding anonymous
credentials, calendar sharing by non-interactive dudle, pub-sub by your
ifip paper, messaging by otpkx, and crowd counting by crocus.

**Comment by sbuc** [comment]
what to get input on
research agenda
look for when purpose/service and privacy can go together
springboard for ideas, early stage
reflect upon surveillance in the digital society by looking at how these practices are constructed, organised, experienced and regulated.
 Resistance towards surveillance - The use of strategies to avoid or disrupt the surveillance mechanisms

**Comment by dbosk** [comment]
Some input from us:
- Here's what we've been working on. Want input on what people actually need? Why do so many not seem to care? What can one do about it?
- Here'e early stage work, we want all sorts of feedback to make it more relevant.

**Comment by dbosk** [comment]
- What do we want people to know?
- What do we want to know (have input on)?

**Comment by sbuc** [comment]
- summary of research done
- early stages: deniability?

**Comment by sbuc** [comment]
- some questions we'd like to discuss, taking advantage of interdisciplinary perspectives

**Comment by dbosk** [comment]
- Many PETs out there, why are they not used more?
- Usability? Encrypt email? Browse web? Is it too difficult, does it introduce problems? Have people tried PETs?
- Is it only the network effect? Can't we do anything?
- What are the obstacles and what can we do to remove the obstacles?

**Comment by sbuc** [comment]
sounds like:
- start with examples people know
- write about existing PETs (by others and us)
- mention some work in progress (deniability and calendar)
- ask about obstacles in PETs adoption to help us improve our work

**Comment by sbuc** [comment]
clarity about whom to protect against, state surveillance (crocus, otpkx), provider (dosn/anobe), other people (calendar, anobe)

**Comment by dbosk** [comment]
Done, it's all in the paper now.
